### PR TITLE
Updated example of cluster configuration

### PR DESCRIPTION
**Pull request by sti-jans**
Hello
  I updated the example.
  But maybe it makes sense to add docker-compose with the cluster and backend configuration?

### CODE REVIEW

**Review by Albibek — APPROVED** [review]

**Comment by Albibek** [comment]
The single docker-compose is not very useful when you only have a bioyno without backends. It probably should be a bit more complex. Still good idea, though.

**Comment by Albibek** [comment]
@sti-jans It would also be great if you put the changes into v0.8.0 branch, which is close to be released. Since there are configuration changes there, it will most probably require to change examples and docker-compose again.

**Comment by sti-jans** [comment]
> The single docker-compose is not very useful when you only have a bioyno without backends. It probably should be a bit more complex. Still good idea, though.

@Albibek Yes, I meant docker-compose together with the backend and may be with Grafana.

> @sti-jans It would also be great if you put the changes into v0.8.0 branch, which is close to be released. Since there are configuration changes there, it will most probably require to change examples and docker-compose again.

When are you planning on releasing version v0.8.0?

**Comment by Albibek** [comment]
> Yes, I meant docker-compose together with the backend and may be with Grafana.
https://github.com/kolobaev/graphite-clickhouse-tldr we've got this one as a reference. May be not very fresh, but gets you to the point.

> When are you planning on releasing version v0.8.0?
I'm only going to make fixes if there are any. We are aready running this one in our production cluster, so It's a matter of few weeks, I think. Please read che CHANGELOG carefully, there are incompatible changes.

**Pull request merged**
